name: oreRush
main: sample.example.oreRush.OreRush
version: '1.1-SNAPSHOT'
api-version: '1.21'
commands:
  oreRush:
database:
  url: "jdbc:mysql://localhost:3306/spigot_server2?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=utf8"
  user: "root"
  password: "1467Ouninn/"
